### ISSUE TITLE
Add links to intro slides for both days

### ISSUE THREAD

**Issue by sstevens2** [UW-Madison-DataScience/2019-06-11-uwmadison-dc#5]
HI @maglet and @tadamus Could you send me your slides or links to your slides to link here?  Or put in a PR if you'd prefer. :-D

**Comment by maglet** [comment]
here you go:

https://docs.google.com/presentation/d/1LVGUI6red04AvFwjhp1q_YRLLGOQiFEdik4pKqtozok/edit#slide=id.g5bd9aa5fed_0_0

(they're in the summer workshop folder)

**Comment by sstevens2** [comment]
Thanks!
